select * from customer.mytable limit 20;
##what is tota revenue generated by male and female?
select gender, sum(purchase_amount) as revenue
from customer.mytable
group by gender;

###which customer's used a discount but stll spend more than the average perchase amount?
select customer_id, purchase_amount
from customer.mytable
where discount_applied = "yes" and purchase_amount >=(select avg(purchase_amount) from customer.mytable);
