select * from customer.mytable limit 20;
##what is tota revenue generated by male and female?
select gender, sum(purchase_amount) as revenue
from customer.mytable
group by gender;

###which customer's used a discount but stll spend more than the average perchase amount?
select customer_id, purchase_amount
from customer.mytable
where discount_applied = "yes" and purchase_amount >=(select avg(purchase_amount) from customer.mytable);

### Q3.Which are the top 5 products with highest average rating?
select item_purchased , round(avg(review_rating),2) as 'highest average rating'
from customer.mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;

###Q4.compare the average purchase amounts between standerd and express shipping?
select shipping_type, round(avg(purchase_amount),2)
from customer.mytable
where shipping_type in ('Standard','Express')
group by shipping_type;

###Q5. Do subscribed customers spend more? compare average spend and total revenue
###between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as average_spend,
round(sum(purchase_amount),2) as total_revenue
from customer.mytable
group by subscription_status
order by total_revenue, average_spend desc;

##Q6 which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
round(100 * SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_applied
from customer.mytable
group by item_purchased
order by discount_applied desc
limit 5;

###Q7. segment customers into new, returning and loyal based on their total no of previous purchases
## and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
from customer.mytable
)

select customer_segment, count(*) as "Number of customer"
from customer_type
group by customer_segment;


## new question by age categories
with age_group as (
select age, purchase_amount,
CASE
   WHEN age = 19 THEN 'Teenager'
   WHEN age BETWEEN 18 AND 25 THEN 'Young Adult'
   WHEN AGE BETWEEN 26 and  56 THEN 'Adult'
   ELSE 'Senior'
   END AS age_categories
from customer.mytable
)

select age_categories, sum(purchase_amount) as total_spend
from age_group 
group by age_categories;

###Q8 what are the top 3 most purchased products within each category
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer.mytable
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;







